### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by joshghent** [maridco/marid-vagrant#10]
Hi,

Having a few issues getting the vagrant to work on my machine.

The $git clone marid-git-url does not seem to work and so I can then not cd into the backend folder. 

Any help appreciated. I do not think this is an issue with the code.

**Comment by nb333** [comment]
cc: @sandlbn

**Comment by sandlbn** [comment]
Hi Josh, 
hmm it's look like issue with the git. Can you try to clone by

git clone https://yourgithubuser@github.com/maridco/marid-vagrant.git

**Comment by joshghent** [comment]
Seemed to get an authentication issue. Weird.

I'll get back to you after doing some more tinkering.

**Comment by turboMaCk** [comment]
are you using SSH or HTTPS?
